import React from 'react';
declare const _default: import("@storybook/types").ComponentAnnotations<import("@storybook/react/dist/types-0a347bb9").R, {
    sets: number[][];
    set_annotations: string[];
    chunks: number[][];
    composition_array: number[][];
    effective_min_width_for_annotation: number;
    col_widths: number[];
    n_items: number;
    ycounts: number[];
    rotate_col_annotations: boolean;
    color_by: "row" | "column";
    color_cycle: string[];
    alternating_background: boolean;
    set_label?: string;
    item_label?: string;
    selection?: Record<string, boolean>;
    onSelectionChange?: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
}>;
export default _default;
export declare const Default: any;
